services:
  watchtower:
    image: containrrr/watchtower:latest
    command:
      - "--label-enable"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=carlotta@carl-otter.lol"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/carlotta/letsencrypt:/letsencrypt
    networks:
      - blackjack

  blackjack:
    image: stauberc/black-jack:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blackjack.rule=Host(`carl-otter.lol`)"
      - "traefik.http.routers.blackjack.entrypoints=websecure"
      - "traefik.http.routers.blackjack.tls=true"
      - "traefik.http.services.blackjack.loadbalancer.server.port=3000"
      - "traefik.http.routers.blackjack.tls.certresolver=myresolver"
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped
    networks:
      blackjack:
        aliases:
          - blackjack

networks:
  blackjack:
    driver: bridge